### ISSUE TITLE
Full multisite support

### ISSUE THREAD

**Issue by mennobouma** [DavidAnderson684/WP-Optimize#65] opened 2015-10-22 12:28 UTC
Hi Ruhani,

Does this plugin gets full multisite support? I mean with global network settings and network optimizing instead of per site? I'm running a big multisite and it's impossible for me to optimize each site one-by-one.

Thanks. Menno

**Comment by joransrb** [comment] 2015-11-15 14:44
I wonder this also...

**Comment by pmsteil** [comment] 2015-11-17 20:30
Also need this, thanks.

**Comment by petebarr** [comment] 2016-08-25 08:30
+1

**Comment by DavidAnderson684** [comment] 2016-12-30 15:39
Duplicate of https://github.com/DavidAnderson684/WP-Optimize/issues/32 - closing.

**Closed by DavidAnderson684** 2016-12-30 15:39 UTC
